### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by ghost** [TritonDataCenter/smartos_cookbooks#3]
I recently forked repository, and had hoped to pull some of the cookbooks out and modify them for my needs. I was in the process of doing so tonight, and notice most of the default recipes say `# All rights reserved - Do Not Redistribute`. 

Worried i may end up getting myself in trouble now by doing so. Can anyone confirm one way or another if I am in the clear, and possibly add a proper license for the repository?

**Comment by benr** [comment]
That should be removed; thanks for being literal but don't worry about it.

**Comment by ghost** [comment]
@benr thanks
